name: Cleanup Closed PR Previews

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove preview for closed PR
        run: |
          rm -rf pr-${{ github.event.pull_request.number }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}" || echo "No changes"
          git push
